# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - compile_and_test:
        requires:
        - resolve_dependencies
      - resolve_dependencies:
        requires:
        - checkout_code


version: 2

defaults: &mavenAndworkdir
  docker:
      # specify the version you desire here
      - image: circleci/openjdk:9-jdk

  working_directory: ~/project



jobs:
  #Phases

  ## Phase Checkout
  checkout_code:
    <<: *mavenAndworkdir

    steps:
      - checkout:
        post:
          - git submodule sync
          - git submodule update --init --recursive

  ## Phase Resolve Deps
  resolve_dependencies:
    <<: *mavenAndworkdir

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

  ## Compile and Run Test Suite
  compile_and_test:
    <<: *mavenAndworkdir

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:

      # run tests!
      - run: mvn clean test