# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

workflows:
  version: 2
  pipeline:
    jobs:
      - checkout_code
      - resolve_dependencies:
          requires:
            - checkout_code
      - compile_and_test:
          requires:
            - resolve_dependencies


version: 2

defaults: &mavenAndworkdir
  docker:
      # specify the version you desire here
      - image: circleci/openjdk:9-jdk
  environment:
    # Customize the JVM maximum heap limit
    MAVEN_OPTS: -Xmx3200m
  working_directory: ~/project



jobs:
  #Phases

  checkout_code:
    <<: *mavenAndworkdir

    steps:
      - checkout

     # Save repo in cache
      - save_cache:
          paths:
            - ~/project
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      # Fetch all git submodules
      - run: git submodule sync
      - run: git submodule update --init --recursive

  ## Phase Resolve Deps
  resolve_dependencies:
    <<: *mavenAndworkdir

    steps:

      # Restore dependencies and repo from cache
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      # Download and cache dependencies
      - run: mvn dependency:go-offline

      # Save dependencies in cache
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

  ## Compile and Run Test Suite
  compile_and_test:
    <<: *mavenAndworkdir

    # Restore dependencies and repo from cache
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-repo-{{ .Environment.CIRCLE_SHA1 }}

    steps:

      # run tests!
      - run: mvn clean test